### ISSUE TITLE
Consider merging scopeId from parent to support scoped styles

### ISSUE THREAD

**Issue by pepf** [alexsasharegan/vue-functional-data-merge#7]
[Over here](https://github.com/vuejs/vue-loader/issues/1136) a bug is described which is about scoped styles not being properly applied when nesting functional components in regular components with scoped styles.

Not every scenario described there might be solvable, but the one where a functional component is nested in a scoped regular component might be.
I did some digging and it turns out the scope id is exposed in the ```$options``` object, so getting it from the parent would be as simple as:
`const scope = this.$parent.$options._scopeId`

With some extra logic, this could make functional components apply the correct scoped styles from the parent when a class attribute has passed overwritten as a prop and the style definition lives in the parent component's scoped stylesheet.

This might not be the intended responsibility of this library, but since it is about increasing the _compatibility_ of functional and regular components within Vue it might be worth to have this fixed here :)

**Comment by alexsasharegan** [comment]
My initial thoughts on this are that this sounds very useful, but slightly off spec as functional components can have scoped styles as well, so they should respect scoping. I see this best as another helper. Any thoughts on that? Would you want to start a pr for this helper? I could pick it up from your beginnings if you're not confident in typescript.

**Comment by pepf** [comment]
I read the following about the intended behavior in the [docs](https://vue-loader.vuejs.org/en/features/scoped-css.html#child-component-root-elements):

> However, a child component's root node will be affected by both the parent's scoped CSS and the child's scoped CSS. This is by design so that the parent can style the child root element for layout purposes.

So it should behave like this (correct me if im wrong)

- scoped parent + a scoped functional child -> two scopes (parent + child scope, on root element)
- scoped parent + a non-scoped functional child -> one scope (the parent one, on root element)
- non-scoped parent + a scoped functional child -> one scope (just its own scope, already works)

This could be done in another helper, but since it modifies the `attrs` part of the componentData you might risk that the two helper functions are conflicting?

I never did typescript but it looks manageable. Ill give it a shot.

**Comment by alexsasharegan** [comment]
Thanks for getting me up to speed! Now I see that this is indeed part of the spec. This should definitely be supported 👍 . If you get started on this before me, go ahead and open a PR as `[WIP]` so I can contribute to your work as I have time, otherwise I will start the WIP PR and you can fork and contribute to that as you have time. If I start it first, I'll ping you so you are aware.

I think the cases you mentioned above are the prime tests to verify this feat/fix implementation.

**Comment by alexsasharegan** [comment]
I'm trying to understand how to implement this, and it seems to me that this should be done in the render function. If `mergeData` did this, it would need the `parent` passed in as a parameter. That breaks the variadic signature of the helper function.

To do this yourself, it would look something like this:

```js
const FunctionalComponent = {
  render(createElement, context) {
    let { parent, data, children } = context;
    let componentData = { attrs: {} };

    if (parent.$options._scopeId) {
      data.attrs[`data-v-${parent.$options._scopeId}`] = "";
    }

    return createElement("div", mergeData(data, componentData), children);
  },
};
```

This could also be extracted into a helper function that could be easily used with the `mergeData` util.

```js
const FunctionalComponent = {
  render(createElement, context) {
    let { parent, data, children } = context;
    let componentData = { class: "my-class" };

    return createElement(
      "div",
      mergeData(data, getStyleScopeData(parent), componentData),
      children
    );
  },
};

/**
 * @param {Vue} parent
 * @returns {VNodeData}
 */
export function getStyleScopeData(parent) {
  let data = {};

  if (parent.$options._scopeId) {
    data.attrs = { [`data-v-${parent.$options._scopeId}`]: "" };
  }

  return data;
}
```

I think this may be too niche too cover in this util. There could be some potential gotchas around the fact that the `parent` property traverses up the tree and is the first instance component that owns it (the functional component). That might not be too much of an issue, but who knows. I'm also concerned that since the `_scopeId` is not documented anywhere, but is instead a byproduct of the loader implementation, it is an unreliable API to depend upon.

In the end, this util is meant to do just one thing, and do it well. I think this does fall just outside that responsibility given the dependency on passing in the parent vue instance.

**Comment by alexsasharegan** [comment]
I added a section of documentation around this topic here: https://github.com/alexsasharegan/vue-functional-data-merge#scoped-styles

**Comment by pepf** [comment]
Fair enough! 
Thanks for looking into it anyway. The arguments you make are pretty valid reasons to stay way from this, but I might look into it anyway since we're extensively using scoped styling in our projects :).

**Comment by alexsasharegan** [comment]
If you come up with something, I would definitely consider putting it in the lib! I usually make these libs from extensive experience with a problem, and I haven't encountered this myself. Since you're in the thick of it, you might come up with a better solution than I would!

**Comment by tmorehouse** [comment]
From what I recall, the scope attribute needs to be placed on _all of the nodes_ in the component, not just the root element, as the scoped style becomes `.class-name[-data-v-${scopeId)]`, and will only apply to element nodes with that attribute.

> The optional scoped attribute automatically scopes this CSS to your component by adding a unique attribute (such as `data-v-21e5b78`) to elements and compiling `.list-container:hover` to something like `.list-container[data-v-21e5b78]:hover`

A directive might be an option (i.e. `v-scoped="$options"`), which traverses the DOM or vDOM and adds the attribute, but then the directive would need to know if the nodes are part of the component or if they belong to sub component or slots (so it can skip over them).  But then again, you might have a child component that you want to scope, but it has child components embedded inside (helper components) that the directive would skip over them when it shouldn't.
